// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOXha7CJ0VE63fzsfhjLKCikzer4XAm5o',
    appId: '1:668875505484:web:db9a4a08d8e982d89699e9',
    messagingSenderId: '668875505484',
    projectId: 'dimplom-project',
    authDomain: 'dimplom-project.firebaseapp.com',
    storageBucket: 'dimplom-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSNuFW0SizcBW0-wr5Y_j7dMYuc74GL90',
    appId: '1:668875505484:android:1007df001386e9bc9699e9',
    messagingSenderId: '668875505484',
    projectId: 'dimplom-project',
    storageBucket: 'dimplom-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASPlHYp52wrYMgjQkOjiKEFPiiLkGR2sA',
    appId: '1:668875505484:ios:14b691c0d9c178da9699e9',
    messagingSenderId: '668875505484',
    projectId: 'dimplom-project',
    storageBucket: 'dimplom-project.appspot.com',
    iosClientId: '668875505484-66bsgfd8h5nbp06mvgrsdg8ea1g6bvji.apps.googleusercontent.com',
    iosBundleId: 'com.example.findHotelsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASPlHYp52wrYMgjQkOjiKEFPiiLkGR2sA',
    appId: '1:668875505484:ios:14b691c0d9c178da9699e9',
    messagingSenderId: '668875505484',
    projectId: 'dimplom-project',
    storageBucket: 'dimplom-project.appspot.com',
    iosClientId: '668875505484-66bsgfd8h5nbp06mvgrsdg8ea1g6bvji.apps.googleusercontent.com',
    iosBundleId: 'com.example.findHotelsApp',
  );
}
