// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs1ptAhr_mW_HvNQqEV7kGMZ3lcqWgkl4',
    appId: '1:12369001857:web:b0fa31279e60c8c71e3c80',
    messagingSenderId: '12369001857',
    projectId: 'diplomchick-33cd4',
    authDomain: 'diplomchick-33cd4.firebaseapp.com',
    storageBucket: 'diplomchick-33cd4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMLPMV1ENImh9tD-CYgVStl3gTPOaIghs',
    appId: '1:12369001857:android:a4c8744f39c816731e3c80',
    messagingSenderId: '12369001857',
    projectId: 'diplomchick-33cd4',
    storageBucket: 'diplomchick-33cd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABc-Jj9wWhn5OteIt3iRYVrOvdWI_nX04',
    appId: '1:12369001857:ios:b1fff98b2b6403d11e3c80',
    messagingSenderId: '12369001857',
    projectId: 'diplomchick-33cd4',
    storageBucket: 'diplomchick-33cd4.appspot.com',
    iosClientId: '12369001857-109flkgdrubu1evg9i9en2tmg9m74pum.apps.googleusercontent.com',
    iosBundleId: 'com.example.findHotelsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABc-Jj9wWhn5OteIt3iRYVrOvdWI_nX04',
    appId: '1:12369001857:ios:b1fff98b2b6403d11e3c80',
    messagingSenderId: '12369001857',
    projectId: 'diplomchick-33cd4',
    storageBucket: 'diplomchick-33cd4.appspot.com',
    iosClientId: '12369001857-109flkgdrubu1evg9i9en2tmg9m74pum.apps.googleusercontent.com',
    iosBundleId: 'com.example.findHotelsApp',
  );
}
